name: deployment
run-name: Handles deployment.
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."
      - run: npm run predeploy
      - run: npm run deploy
